### ISSUE TITLE
Frog does not honour --skip option

### ISSUE THREAD

**Issue by zeusttu** [LanguageMachines/PICCL#28]
We can now select which individual Frog features should and should not run, but it turns out this information is ultimately ignored. I found that `picclservice_wrapper.py` does correctly call `frog.nf` with the correct `--skip` option, but that Frog then proceeds to ignore it. I suspect that the following line is the culprit:
https://github.com/LanguageMachines/PICCL/blob/0d370b84aebf70ddfc6abe906c8eb08429cc120d/frog.nf#L23

**Comment by proycon** [comment]
Hmm, that is odd. That line shouldn't be the issue really cause that's where the defaults are set for the parameters, nextflow superimposes the actual values on it (I guess that happens for each ``process``), but it seems a bit counter-intuitive yes.

**Comment by proycon** [comment]
I think that should fix it.

**Comment by zeusttu** [comment]
I am unfamiliar with the Nextflow language so I believe your word about it. I ran a test and it seems your commit indeed fixed it! :tada: Thanks!

Looking at the code it looks like the same bug should still exist for the `test2folia` workflow though. (We don't use that one but it should still be worth fixing.)
